import { Invitation } from "./types"

export const invitations: Invitation[] = [
  {
    id: 7,
    category: "wedding",
    title: "دعوة زواج — ملكي (وصال)",
    subtitle: "محمد وزينب",
    groom: "محمد",
    bride: "زينب",
    dateGreg: "٢٠ نوفمبر ٢٠٢٦",
    time: "٧:٠٠ مساءً",
    venue: "قاعة بابل الكبرى",
    gradient: ["#1A0E10", "#2A161A", "#1A0E10"],
    accentColor: "#D4AF37",
    tag: "مميز",
    price: "١١٠ ريال",
    verse:
      "وَمِنْ آيَاتِهِ أَنْ خَلَقَ لَكُم مِّنْ أَنفُسِكُمْ أَزْوَاجًا لِّتَسْكُنُوا إِلَيْهَا وَجَعَلَ بَيْنَكُم مَّوَدَّةً وَرَحْمَةً",
    templateType: "wisal",
    heroBg: "/images/hero-bg.jpg",
    introVideo: "/videos/intro.mp4",
    introPoster: "/videos/intro-poster.jpg",
    musicUrl: "/music/background.mp3",
    coverImage: "/mnbra/wedding-01.jpg",
    countdownDate: "2026-11-20T19:00",
  },
  {
    id: 9,
    category: "wedding",
    title: "دعوة زواج — ملكي (وصال)",
    subtitle: "علي وهبة",
    groom: "علي",
    bride: "هبة",
    dateGreg: "٢٠ نوفمبر ٢٠٢٦",
    time: "٧:٠٠ مساءً",
    venue: "قاعة بابل الكبرى",
    gradient: ["#1A0E10", "#2A161A", "#1A0E10"],
    accentColor: "#D4AF37",
    tag: "جديد",
    price: "١١٠ ريال",
    verse:
      "وَمِنْ آيَاتِهِ أَنْ خَلَقَ لَكُم مِّنْ أَنفُسِكُمْ أَزْوَاجًا لِّتَسْكُنُوا إِلَيْهَا وَجَعَلَ بَيْنَكُم مَّوَدَّةً وَرَحْمَةً",
    templateType: "wisal",
    heroBg: "/images/hero-bg-2.jpg",
    introVideo: "/videos/intro-2.mp4",
    introPoster: "/videos/intro-poster-2.jpg",
    musicUrl: "/music/background-2.mp3",
    coverImage: "/mnbra/wedding-02.jpg",
    countdownDate: "2026-11-20T19:00",
  },
]
